### PR TITLE
fix: Right trim URLs before outputting them in getSelector

### LINKED ISSUE #788: Issue when using axe API to get selector of an element
On this url https://support.microsoft.com/en-us/help/12428/microsoft-account-security-info-and-security-codes , get an element using ```document.querySelector("#uhf-c-nav > a[href$="lang "]")``` and try to get the selector of the same element using axe-core API, it will return this ```#uhf-c-nav > a[href$='lang%20'] ```

### PR DESCRIPTION
**Pull request by WilcoFiers**
Closes #788

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message(s) follow our guidelines: https://github.com/dequelabs/axe-core/blob/develop/doc/code-submission-guidelines.md#git-commits
- [ ] Changes to rules and checks appropriately support [Shadow DOM](https://github.com/dequelabs/axe-core/blob/develop/doc/developer-guide.md)
- [ ] Changes have been tested in [major browsers and Assistive Technologies](https://github.com/dequelabs/axe-core/blob/develop/doc/accessibility-supported.md#accessibility-supported)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Description of the changes

- Github issue: Closes #788

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: lib/core/utils/get-friendly-uri-end.js [hunk 1]
```diff
@@ -19,6 +19,10 @@ function splitString (str, splitIndex) {
 	return [str.substring(0, splitIndex), str.substring(splitIndex)];
 }
 
+function trimRight (str) {
```
Comment (jkodu) [inline lib/core/utils/get-friendly-uri-end.js]: Use prototype methods - `.trimRight()` or `.trimEnd()`?
Need IE Support?

Comment (WilcoFiers) [reply lib/core/utils/get-friendly-uri-end.js]: yeah, needs to work in IE.
