### PR TITLE
Sd/region check

### LINKED ISSUE #389: region check - Shadow DOM support
Failing tests for the [region check](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/navigation/region.js):
```
    14) should return true when wrapper content is outside the region
    ✓ should return true when invisible content is outside the region
    ✓ should return true when there is a skiplink
    15) should return false when there is a non-region element
    ✓ should return the first item when after is called
    16) should return false when there is a non-skiplink
```

Subtask of #87.

Full stack trace:
```
14) region should return true when wrapper content is outside the region:
     
  visible@http://localhost:9876/axe.js:9427:31
  checkRegion@http://localhost:9876/tmp/rules.js:1749:72
  map@[native code]
  getViolatingChildren@http://localhost:9876/tmp/rules.js:1759:24
  evaluate@http://localhost:9876/tmp/rules.js:1766:32
  http://localhost:9876/test/checks/navigation/region.js:47:44
  callFn@http://localhost:9876/node_modules/mocha/mocha.js:4447:25
  run@http://localhost:9876/node_modules/mocha/mocha.js:4439:13
  runTest@http://localhost:9876/node_modules/mocha/mocha.js:4936:13
  http://localhost:9876/node_modules/mocha/mocha.js:5042:19
  next@http://localhost:9876/node_modules/mocha/mocha.js:4853:16
  http://localhost:9876/node_modules/mocha/mocha.js:4863:11
  next@http://localhost:9876/node_modules/mocha/mocha.js:4787:16
  http://localhost:9876/node_modules/mocha/mocha.js:4831:9
  timeslice@http://localhost:9876/node_modules/mocha/mocha.js:82:27

  15) region should return false when there is a non-region element:
     expected true to be false
  

  16) region should return false when there is a non-skiplink:
     expected true to be false
```

### PR DESCRIPTION
**Pull request by WilcoFiers**
This closes #389. It reuses parts of #447 and #448.

I found a few problems which this check that I resolved in addition to the shadow DOM work:

- Implicit landmarks were not accepted (e.g. `<main>`)
- Hidden text in things like scripts would be flagged
- The requirement for a skiplink in this check was actually more strict then it is in bypass
- The overall readability of this check wasn’t good

### CODE REVIEW

**Comment by dylanb** [comment]
@WilcoFiers can you rebase this change onto the merged shadowDOM branch?

**Comment by marcysutton** [comment]
We should use `git rebase` and a force push on the branch to avoid merge messages. Or, we could squash this into one commit when we merge it.

File: lib/checks/navigation/region.js [hunk 1]
```diff
@@ -1,34 +1,51 @@
...
+  if (firstLink && axe.commons.dom.getElementByReference(firstLink.actualNode, 'href')) {
+    return firstLink.actualNode;
+  }
+}
 
-var landmarkRoles = axe.commons.aria.getRolesByType('landmark'),
-	firstLink = node.querySelector('a[href]');
+const skipLink = getSkiplink(virtualNode);
+const landmarkRoles = aria.getRolesByType('landmark');
+const implicitLandmarks = landmarkRoles
```
Comment (marcysutton) [inline lib/checks/navigation/region.js]: Can you add a comment about how this code works?

File: test/checks/navigation/region.js [hunk 2]
```diff
@@ -74,9 +66,75 @@ describe('region', function () {
...
 	});
+
+	it('should return true if the non-region element is a script', function () {
+		var checkArgs = checkSetup('<div id="target"><script>axe.run()</script><div role="main">Content</div></div>');
+
+		assert.isTrue(checks.region.evaluate.apply(checkContext, checkArgs));
+	});
+
+	it('should considered aria labelled elements as content', function () {
+		var checkArgs = checkSetup('<div id="target"><div aria-label="axe-core logo"></div><div role="main">Content</div></div>');
```
Comment (marcysutton) [inline test/checks/navigation/region.js]: Shouldn't this DIV have a role on it for `aria-label` to be considered content? It isn't exposed consistently for non-interactive elements or landmarks in my experience

File: test/checks/navigation/region.js [hunk 3]
```diff
@@ -74,9 +66,75 @@ describe('region', function () {
...
+		div.innerHTML = 'Some content';
+		var shadow = div.attachShadow({ mode: 'open' });
+		shadow.innerHTML = '<div role="main"><slot></slot></div>';
+		var checkArgs = checkSetup(div);
+
+		assert.isTrue(checks.region.evaluate.apply(checkContext, checkArgs));
+		assert.lengthOf(checkContext._relatedNodes, 0);
+	});
+
+	(shadowSupport.v1 ? it : xit)('should ignore skiplink targets inside shadow trees', function () {
```
Comment (marcysutton) [inline test/checks/navigation/region.js]: Ooh, good one.

File: test/checks/navigation/region.js [hunk 4]
```diff
@@ -74,9 +66,75 @@ describe('region', function () {
...
+
+		assert.isFalse(checks.region.evaluate.apply(checkContext, checkArgs));
+		assert.deepEqual(checkContext._relatedNodes, [div.querySelector('a')]);
+	});
+
+	(shadowSupport.v1 ? it : xit)('should find the skiplink in shadow DOM', function () {
+		var div = document.createElement('div');
+		div.innerHTML = '<span id="foo">Content!</span>';
+		var shadow = div.attachShadow({ mode: 'open' });
+		shadow.innerHTML = '<a href="#foo">skiplink</a><div role="main"><slot></slot></div>';
```
Comment (marcysutton) [inline test/checks/navigation/region.js]: The href is inside the shadow DOM, but the IDref is in the light DOM...? How does that work?

File: test/checks/navigation/region.js (hunk 2 above)
Comment (WilcoFiers) [inline test/checks/navigation/region.js]: It doesn't matter for the test, but I think you're right. Adding role="img".

File: test/checks/navigation/region.js (hunk 4 above)
Comment (WilcoFiers) [inline test/checks/navigation/region.js]: The `href` attribute isn't an IDREF attribute. It's a URL, which can only point to light DOM IDs/names. Pretty sure longdesc can't point to things inside shadow DOM for the same reason either.

**Comment by WilcoFiers** [comment]
@marcysutton Comments should be resolved. I'll squash moving this into shadowDOM. I had some difficulties rebasing, as it got me conflicts. Wan't too sure how to best get around those. Suggestions?

**Comment by marcysutton** [comment]
I usually resolve the conflicts manually when I rebase. But often for a lot of commits it just isn't worth the time, so a squash and merge is easier.
