### PR TITLE
fix: Do not require media captions / descriptions

### LINKED ISSUE #816: Caption files embedded inside the media wrapper should not fail
Currently it appears that aXe-core is only looking for the presence of the <track> element to deliver caption files, but there is a second method of doing so: place the h.265 encoded video and the AAC encoded audio AND the Vtt/TTML file all inside of the media wrapper (traditionally either .mp4 or .mkv files). 

There is an existing API that "looks inside" the wrapper when being rendered onscreen, which looks for those files to deliver the captioning. Ideally, aXe-core would use a similar method to detect whether the time-stamped file is bundled inside of the media wrapper, as a second test (after checking for the presence of <track> as it does today)

### PR DESCRIPTION
**Pull request by WilcoFiers**
Do not require media captions / descriptions
Closes #816 

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: @jkodu

### CODE REVIEW

File: build/tasks/validate.js [hunk 1]
```diff
@@ -27,6 +27,27 @@ function hasUniqueId() {
 	};
 }
 
+function hasTwoOutcomes(messages) {
```
Comment (jkodu) [inline build/tasks/validate.js]: Looks like this is normalising multiple outcomes, should change function name to something generic like `normaliseOutcomes` or `hasMultipleOutcomes` rather than exactly `Two`?

File: build/tasks/validate.js [hunk 2]
```diff
@@ -84,16 +105,20 @@ function createSchemas() {
...
-							},
-							pass: {
-								required: true,
-								type: 'string'
-							}
+						conform: hasTwoOutcomes,
+						messages: {
+							conform: 'Must have at least two valid messages'
 						}
+						// propferties: {
```
Comment (jkodu) [inline build/tasks/validate.js]: minor: 🤣 `propferties`, know it is commented.... delete instead?

Comment (dylanb) [reply build/tasks/validate.js]: yeah, delete this comment

File: lib/checks/media/caption.json [hunk 3]
```diff
@@ -5,7 +5,6 @@
     "impact": "critical",
     "messages": {
       "pass": "The multimedia element has a captions track",
-      "fail": "The multimedia element does not have a captions track",
       "incomplete": "A captions track for this element could not be found"
```
Comment (dylanb) [inline lib/checks/media/caption.json]: Could make this message more explicit about what to do to check whether an alternative exists

**Comment by WilcoFiers** [comment]
@dylanb @jkodu Updated the PR.
