### PR TITLE
fix(aria-allowed-role): Allow iframe role=none [#1360]

### LINKED ISSUE #1360: Iframe fails with role presentation
Expectation: The following code should not identify it as a best practice
<code><iframe role="presentation"></iframe></code>
Providing an role presentation on iframe is allowed

Actual: aXe extension throws best practice violation aganist an iframe with role presentation

<pre><code>
axe-core version: 3.1.2
</code></pre>

### PR DESCRIPTION
**Pull request by WilcoFiers**
As reported by Soma, iframes should be allowed role=none|presentation. See:
https://www.w3.org/TR/html-aria/#iframe

Closes #1360 

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: Steve

### CODE REVIEW

**Comment by straker** [comment]
LGTM

File: lib/commons/aria/index.js [hunk 1]
```diff
@@ -1407,9 +1407,11 @@ lookupTable.role = {
 					'h5',
 					'h6',
 					'header',
+					'iframe',
 					'li',
+					'ol',
 					'section',
-					'ol'
+					'ul'
```
Comment (dylanb) [inline lib/commons/aria/index.js]: Why this addition?

Comment (WilcoFiers) [reply lib/commons/aria/index.js]: Not sure how this got overlooked, but it the spec says these are allowed.
