### PR TITLE
fix(aria-allowed-attr): pass aria-expanded on checkbox & switch

### LINKED ISSUE #3339: roles that allow aria-expanded and aria-roles.js question
ARIA 1.2 has fixed an error where ARIA 1.1 allowed `aria-expanded` on a number of elements that didn't make sense.  e.g., `role=alert aria-expanded=...`.  [ARIA issue where this topic was discussed](https://github.com/w3c/aria/issues/681) - fixed in 2019, so has been part of the initial and current ARIA 1.2 CR draft.

I noticed in the aria-roles.js file that `aria-expanded` is still marked as an allowed attribute on these roles, which at first made sense to me because the file notes on the first line that it is referencing ARIA 1.1... so since they were allowed then, if axe is still referencing ARIA 1.1 then they would still be allowed, though their use by authors is suspect / probably incorrect.   

However, upon further review of the file, there are a number of roles that were introduces in ARIA 1.2 that are also included... which again also makes sense as many of them have been implemented by browsers... but this then made me wonder if it would be a good idea for axe to also correct the `aria-expanded` allowances, even though the correction is tied to ARIA 1.2.  

Regardless of when axe might want to pull in the correction, I'd be happy to create a PR to remove the `aria-expanded` allowances from the necessary roles in this file.

### PR DESCRIPTION
**Pull request by WilcoFiers**
WAI-ARIA 1.3 has proposed to dramatically change which roles allow aria-expanded. Per this PR, `checkbox` and `switch` now allow this attribute. Quite a few more roles no longer allow `aria-expanded`.

I've opened up an issue requesting that ARIA 1.3 deprecate aria-expanded on those roles, instead of simply removing them. I think simply removing them would create a lot of unnecessary friction. If the W3C decides not to stay backward compatible we may have to figure out a different way to present this, but by far the best solution here would be to use deprecation, which is what they've also done in other places. See https://github.com/w3c/aria/issues/1990

Closes #3339, closes #3343

### CODE REVIEW

File: lib/standards/aria-roles.js [hunk 1]
```diff
@@ -775,15 +812,19 @@ const ariaRoles = {
   },
   time: {
     type: 'structure',
+    // Aria-expanded removed as of 1.3
+    allowedAttrs: ['aria-expanded'],
```
Comment (straker) [inline lib/standards/aria-roles.js:816]: Did you mean to add this?

```suggestion
```

**Review by straker — CHANGES_REQUESTED** [review]

**Review by straker — APPROVED** [review]

**Review by dbjorge — APPROVED** [review]
