### PR TITLE
fix: td-has-heading to ignore td with its role changed

### LINKED ISSUE #888: False positive: 'td-has-header' fails for cells having 'role=columnheader' or 'role=rowheader' as headers
- Demo:
```
Case-1:
    <table id="table-1">
        <tr>
            <td role="columnheader">Name</td>
            <td role="columnheader">Age</td>
            <td role="columnheader">Height (cm)</td>
            <td role="columnheader">Weight (kg)</td>
        </tr>

        <tr>
            <td>Linda</td>
            <td>33</td>
            <td>169</td>
            <td>59</td>
        </tr>

        <tr>
            <td>Jack</td>
            <td>37</td>
            <td>184</td>
            <td>74</td>
        </tr>

        <tr>
            <td>Kira</td>
            <td>8</td>
            <td>120</td>
            <td>21</td>
        </tr>

        <tr>
            <td>Daniel</td>
            <td>3</td>
            <td>79</td>
            <td>14</td>
        </tr>
    </table>

Case-2:
 <table id="table-2">
        <tr>
            <td role="rowheader">Name</td>
            <td>Linda</td>
            <td>Jack</td>
            <td>Kira</td>
            <td>Daniel</td>
        </tr>

        <tr>
            <td role="rowheader">Age</td>
            <td>33</td>
            <td>37</td>
            <td>8</td>
            <td>3</td>
        </tr>

        <tr>
            <td role="rowheader">Height (cm)</td>
            <td>169</td>
            <td>184</td>
            <td>120</td>
            <td>79</td>

        </tr>

        <tr>
            <td role="rowheader">Weight (kg)</td>
            <td>59</td>
            <td>74</td>
            <td>21</td>
            <td>14</td>
        </tr>
    </table>
```

<pre><code>axe-core version: 3.0.0-beta.3
axe-Coconut version: 3.3.0-beta.0
</code></pre>

### PR DESCRIPTION
**Pull request by WilcoFiers**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message(s) follow our guidelines: https://github.com/dequelabs/axe-core/blob/develop/doc/code-submission-guidelines.md#git-commits
- [x] Changes to rules and checks appropriately support [Shadow DOM](https://github.com/dequelabs/axe-core/blob/develop/doc/developer-guide.md)
- [ ] Changes have been tested in [major browsers and Assistive Technologies](https://github.com/dequelabs/axe-core/blob/develop/doc/accessibility-supported.md#accessibility-supported)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Description of the changes

- Github issue: closes #888

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: test/commons/table/is-data-cell.js [hunk 1]
```diff
@@ -40,4 +40,42 @@ describe('table.isDataCell', function () {
...
+
+		var target1 = $id('target1');
+		var target2 = $id('target2');
+		var target3 = $id('target3');
+		assert.isFalse(axe.commons.table.isDataCell(target1));
+		assert.isFalse(axe.commons.table.isDataCell(target2));
+		assert.isFalse(axe.commons.table.isDataCell(target3));
+	});
+
+	it('should return true for elements with role="(grid)cell"', function () {
```
Comment (jkodu) [inline test/commons/table/is-data-cell.js]: `role="(grid)cell"` - what is the intention behind the brackets around (grid)?

Comment (WilcoFiers) [reply test/commons/table/is-data-cell.js]: `role=gridcell` and `role=cell` I don't see the point of separate cases. It's the same functionality. It's just data.
