### PR TITLE
fix(label-content-name-mismatch): ignore private space unicode

### LINKED ISSUE #1635: false positive on label-content-name-mismatch rule
The rule seems to evaluate the innerText value & compares it with the aria-label value. This results in false positive, when we have icon as a child element that has some content, even though visually the user only sees icon instead of text.
eg where it fails:
```
<a id="link1" tabindex="0" href="./some-link" aria-label="Favorites">
  <div><span aria-hidden="true" class="some-icon"></span></div>
  <div><span aria-hidden="true">Favorites</span></div>
</a>
```
https://codepen.io/devaradhanm/pen/xoZdmd

including @iamrafan , for his inputs too.

### PR DESCRIPTION
**Pull request by straker**
Part 1 for #1635 to fix using private use unicode characters. 

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [x] Follows the commit message policy, appropriate for next version
- [x] Code is reviewed for security

### CODE REVIEW

File: lib/commons/text/unicode.js [hunk 1]
```diff
@@ -91,6 +91,7 @@ function getUnicodeNonBmpRegExp() {
 		'\u25A0-\u25FF' + // Geometric Shapes
 		'\u2600-\u26FF' + // Misc Symbols
 		'\u2700-\u27BF' + // Dingbats
+		'\uE000-\uF8FF' + // Private Use
```
Comment (jkodu) [inline lib/commons/text/unicode.js]: Going with definition from here:

>  Does Unicode have private-use characters?

> A: Yes. There are three ranges of private-use characters in the standard. The main range in the BMP is U+E000..U+F8FF, containing 6,400 private-use characters. That range is often referred to as the Private Use Area (PUA). But there are also two large ranges of supplementary private-use characters, consisting of most of the code points on Planes 15 and 16: U+F0000..U+FFFFD and U+100000..U+10FFFD. Together those ranges allocate another 131,068 private-use characters. Altogether, then, there are 137,468 private-use characters in Unicode.

It looks like we are only ignoring ones in BMP and not the supplementary private-use characters. Shouldn't we consider the supplementary ones too?

Comment (straker) [reply lib/commons/text/unicode.js]: I thought about it, but I haven't been able to find a 100% reliable way to test them. I wasn't able to find anything directly on the internet, but was able to piece together how we might be able to using surrogate pairs of the [high](https://www.unicode.org/charts/PDF/UD800.pdf) and [low](https://www.unicode.org/charts/PDF/UDC00.pdf) surrogates together. Theoretically this regex should catch them, but I can't be sure.

```
/[\uDB80-\uDBBF][\uDC00-\uDFFD]/
```

Comment (WilcoFiers) [reply lib/commons/text/unicode.js]: Given that nothing in that range is likely to be something Dragon knows how to handle, I think it's a pretty safe bet to just exclude the entire range.
