### PR TITLE
Fix viewport scroll bug

### LINKED ISSUE #147: Running the audit scrolls the viewport to the bottom of the page
When I run the audit, the viewport scrolls to the bottom of the page. This can be reproduced by running the axe extension in Firefox or running the javascript in console.

### PR DESCRIPTION
**Pull request by ckundo**
- Running the audit before would scroll the viewport to the bottom of the page.

[Closes #147]

### CODE REVIEW

**Comment by ckundo** [comment]
Phantomjs is hanging locally, waiting to see what CI says.

**Comment by dylanb** [comment]
@ckundo this call is required in order to make the color contrast checks work in all instances on all browsers. The only way to make this a little better would be to remember the scroll position at the beginning of an audit and then restore it at the end. This would make the browser scroll a bit but would restore it. If you'd like to make a change like that, it would be a welcome change...

**Comment by ckundo** [comment]
Thanks @dylanb, I thought of returning focus. That'd be an improvement, but the jumpiness would still be distracting. Do you know which browsers/scenarios require this? I could work on a configuration option like `{ "browsers": ["IE-9+", "Firefox", ...] }` that we could use to toggle features like this.

**Comment by dylanb** [comment]
@ckundo what is your use case? If we put browser-specific code into the library, then your use case would only "work" in the browsers that do not suffer from the problem, so the question would be, why not simply turn off the color contrast rule if you do not want this behavior?

**Comment by ckundo** [comment]
@dylanb I'm including and running the audit automatically on a page. I was thinking that running the audit without the `scrollIntoView` could at least give results for browsers that don't require the node to be in the viewport, and silently pass on other browsers. That'd mean false negatives for some browsers.

**Comment by dylanb** [comment]
@ckundo it could mean false positives too because of the nature of that issue, the end result will be the background always being calculated as white. This could lead to dark backgrounds causing lots of false positives.

I am not sure of the complete list of browsers that exhibit this problem. I know for a fact that Firefox does.

**Comment by ckundo** [comment]
@dylanb got it, yes that makes sense about the false positives. What I'd like to do in that case is have the option to run the rule without scrolling, and then disable the rule in my app, except in a whitelisted set of browsers that I know will work without scroll. That means that axe-core would need to accept a configuration option to disable the scroll. Is that something you'd entertain?

**Comment by dylanb** [comment]
@ckundo An option would be better how were you thinking of implementing and calling the option?

You could pass back `null` from `getBackgroundColor` which would result in false negatives - which this rule suffers from anyway due to background images and gradients.

**Comment by ckundo** [comment]
@dylanb I updated the PR with a possible solution to accept a "noScroll" option to the rule: https://github.com/dequelabs/axe-core/commit/24b3879acb0bf25aac2b7de9a6b83af9868b5fc5

**Comment by dylanb** [comment]
On a quick perusal of the changes that looks good to change the util function. You would need to make a change to the check to make use of this.

**Comment by dylanb** [comment]
Here is an example of a check using options

https://github.com/dequelabs/axe-core/blob/master/lib/checks/language/valid-lang.js#L5

and the options in the .json file

https://github.com/dequelabs/axe-core/blob/master/lib/checks/language/valid-lang.json

File: lib/commons/color/get-background-color.js [hunk 1]
```diff
@@ -108,11 +108,13 @@ var getVisualParents = function(node, rect) {
...
  * @param {Element} node
  * @param {Array} bgNodes array to which all encountered nodes should be appended
+ * @param {Object} options
  * @return {Color}
  */
 //TODO dsturley; why is this passing `bgNodes`?
-color.getBackgroundColor = function(node, bgNodes) {
+color.getBackgroundColor = function(node, bgNodes, options) {
 	var parent, parentColor;
+	var options = options || {};
```
Comment (dylanb) [inline lib/commons/color/get-background-color.js]: Should remove the var in this line as options is already defined

**Comment by dylanb** [comment]
There are a bunch of lint problems with the code changes, you should fix those too

File: lib/checks/color/color-contrast.js [hunk 2]
```diff
@@ -1,6 +1,12 @@
+var useScroll = true;
+
+if((options || []).indexOf('noScroll') !== -1) {
```
Comment (ckundo) [inline lib/checks/color/color-contrast.js]: @dylanb is this what you had in mind regarding options? The default will be to always scroll, unless the options array includes the string `"noScroll"`.

File: lib/commons/color/get-background-color.js [hunk 3]
```diff
@@ -1,5 +1,5 @@
 /*global dom, color */
-/* jshint maxstatements: 31, maxcomplexity: 14 */
+/* jshint maxstatements: 32, maxcomplexity: 15 */
```
Comment (ckundo) [inline lib/commons/color/get-background-color.js]: I gave a shot at refactoring this to reduce complexity here: https://github.com/ckundo/axe-core/commit/2cac6de1dbcf2fdcbcebb2b3f636124cd6609619
I still had a failing test and gave up on it.

File: lib/rules/color-contrast.json [hunk 4]
```diff
@@ -1,5 +1,6 @@
 {
   "id": "color-contrast",
+  "options": [],
```
Comment (ckundo) [inline lib/rules/color-contrast.json]: Should this default to empty?

**Comment by ckundo** [comment]
@dylanb I went ahead with the changes you recommended, appeased jslint, and squashed the commits with a better commit message.

File: lib/rules/color-contrast.json (hunk 4 above)
Comment (dylanb) [inline lib/rules/color-contrast.json]: I think it should default to false so that it is self-documenting

**Comment by dylanb** [comment]
Here is an example of a custom call to configure

```
axe.configure({
	checks: [{
      id: "valid-lang",
      options: [ "dylan" ],
      evaluate: function(node, options) {
        var lang = (node.getAttribute("lang") || "").trim().toLowerCase();
        var xmlLang = (node.getAttribute("xml:lang") || "").trim().toLowerCase();
        var invalid = [];
        (options || []).forEach(function(cc) {
          cc = cc.toLowerCase();
          if (lang && (lang === cc || lang.indexOf(cc.toLowerCase() + "-") === 0)) {
            lang = null;
          }
          if (xmlLang && (xmlLang === cc || xmlLang.indexOf(cc.toLowerCase() + "-") === 0)) {
            xmlLang = null;
          }
        });
        if (xmlLang) {
          invalid.push('xml:lang="' + xmlLang + '"');
        }
        if (lang) {
          invalid.push('lang="' + lang + '"');
        }
        if (invalid.length) {
          this.data(invalid);
          return true;
        }
        return false;
      }
	}],
	rules:[]
})
```

File: lib/checks/color/color-contrast.js (hunk 2 above)
Comment (dylanb) [inline lib/checks/color/color-contrast.js]: The options can be anything you specify. In this case, I think it would be better to make it an object with an attribute that is a boolean (truthy test), I would suggest changing this to:

```
if (!(options || {}).noScroll) {
```

and making the appropriate changes to the options below

File: test/commons/color/get-background-color.js [hunk 5]
```diff
@@ -259,6 +259,19 @@ describe('color.getBackgroundColor', function () {
...
+		var targetEl = fixture.querySelector('#target');
+		var bgNodes = [];
+		var useScroll = false;
+		window.scroll(0, 0);
 
+		commons.color.getBackgroundColor(targetEl, bgNodes, useScroll);
 
+		assert.equal(window.pageYOffset, 0);
+		assert.equal(window.pageXOffset, 0);
+	});
```
Comment (dylanb) [inline test/commons/color/get-background-color.js]: @ckundo you should probably add a test that tests to ensure that no scrolling occurs when the option is enabled - WDYT?

**Comment by dylanb** [comment]
@ckundo just checkin to see if you are working on responses to the comments?

**Comment by ckundo** [comment]
Hi Dylan, yes, I'll be updating the PR soon.

**Comment by dylanb** [comment]
Awesome!!

**Comment by dylanb** [comment]
@ckundo how is the PR going?

**Comment by ckundo** [comment]
Oof, sorry for dropping this. I'm still interested in finishing it off, and have some time this week. Will work on it.

File: lib/checks/color/color-contrast.js [hunk 6]
```diff
@@ -1,6 +1,12 @@
+var useScroll = true;
+
+if((options || {}).noScroll) {
```
Comment (ckundo) [inline lib/checks/color/color-contrast.js]: @dylanb you had suggested using negation here. Were you thinking initializing `useScroll` to false on line 1, then setting it to `true` if this expression is truthy?

**Comment by ckundo** [comment]
@dylanb I made changes based on your comments. Do you want me to squash these commits so we can merge?

File: lib/checks/color/color-contrast.js (hunk 6 above)
Comment (dylanb) [inline lib/checks/color/color-contrast.js]: I was suggesting the following to shorten this

```
var useScroll = !((options || {}).noScroll);
```

**Comment by dylanb** [comment]
yeah, if you could squash these commits then I'll merge

**Comment by ckundo** [comment]
@dylanb all set!

**Comment by WilcoFiers** [comment]
@ckundo I've looked at your changes. The problem is that without scrolling, there are quite a few scenario's where we're not going to be able to find the correct ancestors. So please be aware that some of the 'passes' might come from not being able to look at the contrast difference, similar to how aXe doesn't look at contrast with background images. We are working on a feature which will improve on this.

**Comment by ckundo** [comment]
thanks @wilco, that makes sense to me. Worth noting that in the case of phantomjs, I think it should work fine because one can load the whole page. But for client side injection I can see the concern for false negatives. Thanks!

**Comment by ckundo** [comment]
@dylanb did this ever get released to npm? I'm not seeing the changes in axe.js in the node module.

**Comment by seancurtis** [comment]
I'm also wondering why I'm still seeing this behaviour. We added some a11y checking to our React Storybook but now all story pages get scrolled to the bottom automatically. It's very frustrating.

**Comment by seancurtis** [comment]
Seems like it was changed from useScroll to noScroll. Does that mean it only checks things within the viewport? Can't it just record the offset at the start of the check and set it back to that at the end?

**Comment by dylanb** [comment]
@seancurtis we are working on a reset of the scroll and a new implementation of the scrolling in the first place. Stay tuned for that.

Also: we need both a reset and the "noScroll" option because dynamic analysis implementations (like react-axe) will want to avoid scrolling at all because of the flicker that can induce (even if it resets).

**Comment by ndelangen** [comment]
I just found out about this, but it seems this disable scrolling feature is rather hidden away and undocumented.

Would a top level `noScroll` option make sense?
like `restoreScroll`?

Would an enum option like this make sense ?
```
scrollBehavior: 'disabled' | 'enabled' | 'restore'
```
