### PR TITLE
fix: Let findUp work on shadow root children

### LINKED ISSUE #422: "aria-required-parent" check to use the composed tree in getAriaOwners
"aria-required-parent" check to use the composed tree in getAriaOwners

### PR DESCRIPTION
**Pull request by WilcoFiers**
Should help resolve #422.

### CODE REVIEW

File: lib/commons/dom/find-up.js [hunk 1]
```diff
@@ -9,33 +9,24 @@
  * @return {HTMLElement|null} Either the matching HTMLElement or `null` if there was no match
  */
 dom.findUp = function (element, target) {
-	'use strict';
```
Comment (dylanb) [inline lib/commons/dom/find-up.js]: These changes don't seem to actually change anything in terms of functionality - is this purely a performance fix?

Comment (dylanb) [inline lib/commons/dom/find-up.js]: ok, so the difference here is that if the starting node is the highest node in the shadow DOM, then the old code did not find a matching host node - whereas this code does?

File: test/commons/dom/find-up.js [hunk 2]
```diff
@@ -107,12 +117,22 @@ describe('dom.findUp', function () {
...
+
+		fixture.innerHTML = '<label><div></div></label>';
+		makeShadowTree(fixture.querySelector('div'));
+		var tree = axe.utils.getFlattenedTree(fixture.firstChild);
+		var el = axe.utils.querySelectorAll(tree, 'a')[0];
+		assert.equal(axe.commons.dom.findUp(el.actualNode, 'label'), fixture.firstChild);
+	});
+
+	(shadowSupport.v1 ? it : xit)('should work on shadow root children', function () {
+		fixture.innerHTML = '<div role="list"><div id="something"></div></div>';
```
Comment (dylanb) [inline test/commons/dom/find-up.js]: shouldn't this attach to the div with role="list"?

File: lib/commons/dom/find-up.js (hunk 1 above)
Comment (WilcoFiers) [inline lib/commons/dom/find-up.js]: The problem is that if the child is a directly on the shadow root, it would start looking from the host (outside the shadow), even though the matches array still only contained elements inside the shadow tree.

Followup thought, should this use element.matches() instead of doing querySelectAll() and see if the element is included? I imagine that'd be faster.

Comment (WilcoFiers) [inline lib/commons/dom/find-up.js]: The problem is that if the child is a directly on the shadow root, it would start looking from the host (outside the shadow), even though the matches array still only contained elements inside the shadow tree.

Followup thought, should this use element.matches() instead of doing querySelectAll() and see if the element is included? I imagine that'd be faster.
