### PR TITLE
fix(color-contrast): do not run on elements with font-size: 0

### LINKED ISSUE #4820: False positive color-contrast: `font-size: 0` elements should be ignored
This came up recently where an element with `font-size: 0` is throwing a color-contrast violation when the text is not visible. Normally an element with `font-size: 0` would have a width and height of 0 (which should be ignored), but explicitly setting the width and height of the element overrides that while still visually hidding the font.

```html
<ol>
  <li>Visible text</li>
  <li style="font-size: 0; width: 16px; height: 16px; background: red; color: #282828;">Not visible</li>
</ol>
```

### PR DESCRIPTION
**Pull request by straker**
Closes #4820

### CODE REVIEW

File: lib/rules/color-contrast-matches.js [hunk 1]
```diff
@@ -137,6 +137,10 @@ function colorContrastMatches(node, virtualNode) {
     return false;
   }
 
+  if (virtualNode.getComputedStylePropertyValue('font-size') === '0px') {
```
Comment (nickbrit) [inline lib/rules/color-contrast-matches.js]: I’d like to suggest a small update for the font‑size check:

```
// Skip elements with zero or invalid font size
if (!parseFloat(virtualNode.getComputedStylePropertyValue('font-size'))) {
    return false;
}
```

Hope this helps!

Comment (WilcoFiers) [reply lib/rules/color-contrast-matches.js]: I agree, that seems safer.

File: test/rule-matches/color-contrast-matches.js [hunk 2]
```diff
@@ -431,6 +431,13 @@ describe('color-contrast-matches', function () {
     assert.isFalse(rule.matches(target, axe.utils.getNodeFromTree(target)));
   });
 
+  it('should not match text with font-size: 0', () => {
```
Comment (WilcoFiers) [inline test/rule-matches/color-contrast-matches.js:434]: Let's add an integration test too.

**Review by WilcoFiers — DISMISSED** [review]

**Review by WilcoFiers — APPROVED** [review]
