### PR TITLE
fix(rules/region): Treat <section> as a landmark if it has an accessible name #640

### LINKED ISSUE #640: Rule: 'region' - <section> element with non-empty 'aria-label' or 'aria-labelledby' or 'title' attributes is not being detected as a landmark
```
<section aria-label="name1">
        <h1>Section-1: With aria-label</h1>
        <p>Content 1: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua</p>
    </section>

    <section aria-labelledby="name2">
        <h1 id="name2">Section-2: With aria-labelledby</h1>
        <p>Content 2: Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
    </section>

    <section title="name3">
        <h1>Section-3: With title</h1>
        <p>Content 3: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
    </section>
```

### PR DESCRIPTION
**Pull request by WilcoFiers**
This closes #640.

### CODE REVIEW

File: lib/checks/navigation/region.js [hunk 1]
```diff
@@ -26,7 +26,9 @@ function isLandmark (node) {
 	if (node.hasAttribute('role')) {
 		return landmarkRoles.includes(node.getAttribute('role').toLowerCase());
 	} else {
-		return implicitLandmarks.includes(node.nodeName.toUpperCase());
+		return implicitLandmarks.some((implicitSelector) => {
```
Comment (marcysutton) [inline lib/checks/navigation/region.js]: That looks like magic to me. Can you add a comment about what's happening here?

Comment (isner) [reply lib/checks/navigation/region.js]: Looks like he's electing to use the `matchesSelector` utility to determine whether the node has an implicit landmark role, instead of simply checking whether the array of of implicit landmark roles includes the nodeName. I'm guessing this wasn't working for all nodes, since the nodeName of an element with an implicit landmark role is often different than the landmark role. E.g., given a `<header>` element, `#nodeName === 'HEADER'`, but its implicit role is 'banner'.

Comment (isner) [reply lib/checks/navigation/region.js]: This also allows the values in the role's "implicit" entry in the lookup table to be CSS selectors more complex than just the nodeName. E.g., `input[type="button"]`

Comment (marcysutton) [reply lib/checks/navigation/region.js]: Thanks! I'd still love to see a comment in the code for future reading.

**Comment by WilcoFiers** [comment]
Also merged into 2x

**Comment by iamrafan** [comment]
@WilcoFiers Thank you
