### PR TITLE
fix: Allow only-dlitem / only-listitem to have any hidden content

### LINKED ISSUE #1021: only-listitems and only-dlitems pick up hidden <dom-repeat> as disallowed child
As discussed on slack with @marcysutton and @alice. 

When creating a `<ul>`, `<ol>` or `<dl>` using `<dom-repeat>`, you get a `<dom-repeat style="display:none">` inside your list, alongside the listitems. Both `only-listitems` and `only-dlitems` report this as an issue, as the `<dom-repeat>` is not one of the `ALLOWED_TAGS` in the rule, and it ignores the fact the element is hidden with `display:none`.
`display:none` should be taken in consideration as it hides the element from the accessibility tree.

[Example](https://next.plnkr.co/edit/3AD8dwuF30hoRXjI)

Also, the pass and fail messages are incorrect for both rules. For example, the pass for `only-listitems` states `List element only has direct children that are allowed inside <li> elements`. The rule does not check for what is inside `<li>` elements, but what's inside `<ul>` or `<ol>` elements.

### PR DESCRIPTION
**Pull request by WilcoFiers**
This change allows any hidden element in ul, ol and dl elements.

Closes #1021 

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [ ] Follows the commit message policy, appropriate for next version
- [ ] Has documentation updated, a DU ticket, or requires no documentation change
- [ ] Includes new tests, or was unnecessary
- [ ] Code is reviewed for security by: << Name here >>

### CODE REVIEW

File: test/checks/lists/only-dlitems.js [hunk 1]
```diff
@@ -194,6 +194,42 @@ describe('only-dlitems', function() {
...
+	it('returns false if there are visibility:hidden elements that normally would not be allowed', function() {
+		var checkArgs = checkSetup(
+			'<dl id="target"> <dt>An item</dt> <dd>A list</dd> <h1 style="visibility:hidden">heading</h1> </dl>'
+		);
+		assert.isFalse(
+			checks['only-dlitems'].evaluate.apply(checkContext, checkArgs)
+		);
+	});
+
+	it('returns false if there are aria-hidden=true elements that normally would not be allowed', function() {
```
Comment (dylanb) [inline test/checks/lists/only-dlitems.js]: hmmm, I don't agree with this case

File: test/checks/lists/only-listitems.js [hunk 2]
```diff
@@ -189,6 +189,42 @@ describe('only-listitems', function() {
...
+	it('returns false if there are visibility:hidden elements that normally would not be allowed', function() {
+		var checkArgs = checkSetup(
+			'<ul id="target"> <li>An item</li> <h1 style="visibility:hidden">heading</h1> </ul>'
+		);
+		assert.isFalse(
+			checks['only-listitems'].evaluate.apply(checkContext, checkArgs)
+		);
+	});
+
+	it('returns false if there are aria-hidden=true elements that normally would not be allowed', function() {
```
Comment (dylanb) [inline test/checks/lists/only-listitems.js]: I disagree with this

**Comment by dylanb** [comment]
ok, I was mistaken in thinking this was a 4.1.1 rule and not a 1.3.1 rule
