### PR TITLE
Fix `getSelector` for namespaced elements + introduce XHTML fixtures

### LINKED ISSUE #563: aXe fails on XHTML documents with prefixed element names
When ran against an XHTML document with namespaced elements, aXe crashes with a syntax error on the `matchesSelector` function.

This is due to the selector creation using the element’s `nodeName`, which results in an (invalid) selector of the form `prefix:name`.

Since the DOM Standard [doesn't plan to support namespaces with selectors](https://dom.spec.whatwg.org/#scope-match-a-selectors-string), the best approach would probably be to use the element’s local name as the selector (instead of the prefixed node name).

This can be reproduced with the following document:

```xml
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta charset="utf-8" />
  <title>Math Sample</title>
</head>
<body>
<h1>Math Sample</h1>
<m:math alttext="x" xmlns:m="http://www.w3.org/1998/Math/MathML">
  <m:semantics>
    <m:mi>x</m:mi>
    <m:annotation-xml encoding="MathML-Content">
      <m:ci>x</m:ci>
    </m:annotation-xml>
  </m:semantics>
</m:math>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by rdeltour**
Replaces #566
Closes #563

### CODE REVIEW

**Comment by rdeltour** [comment]
Not quite sure what should I do about the codacy checks, I tried to follow the code style from the other files. Please LMK if you want me to update the PR!

**Comment by marcysutton** [comment]
Thanks @rdeltour! The codacy thing was just added but it conflicts with our jshint rules, so you can probably disregard for now.

**Comment by WilcoFiers** [comment]
Apologies. I meant to delete the Codacy hook but I hadn't done so yet. Shouldn't turn up on new commits anymore.

File: test/core/utils/is-xhtml.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
+describe('axe.utils.isXHTML', function () {
+	'use strict';
+
+	it('should be a function', function () {
+		assert.isFunction(axe.utils.isXHTML);
+	});
+
+	it('should return true on any document that is XHTML', function () {
+		var doc = document.implementation.createDocument('http://www.w3.org/1999/xhtml', 'html', null);
```
Comment (marcysutton) [inline test/core/utils/is-xhtml.js]: I had no idea this interface existed. 

the-more-you-know

File: test/xhtml/core/utils/is-xhtml.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+describe('axe.utils.isXHTML', function () {
```
Comment (marcysutton) [inline test/xhtml/core/utils/is-xhtml.js]: I don't think you need this file, it's redundant with `test/core/utils/is-xhtml.js`.

File: test/xhtml/core/utils/get-selector.js [hunk 3]
```diff
@@ -0,0 +1,24 @@
+
+describe('axe.utils.getSelector', function () {
```
Comment (marcysutton) [inline test/xhtml/core/utils/get-selector.js]: It's a little strange to have a test for `get-selector` duplicated in another directory. Can you make it work in the existing core unit tests by creating a document like in `test/core/utils/is-xhtml.js`?

**Comment by rdeltour** [comment]
Thank you @marcysutton for the review!

re:
> It's a little strange to have a test for get-selector duplicated in another directory. Can you make it work in the existing core unit tests by creating a document like in test/core/utils/is-xhtml.js?

and

> I don't think you need this file, it's redundant with test/core/utils/is-xhtml.js.

let me try to explain why I did this:

As far as I understand, all aXe’s tests are run in an HTML fixture, injected in the `runner.tmpl` template. It means that in those tests, the DOM is **always** an HTML document.

But for some tests, I needed to be in an XHTML context. So, I created another fixture. All the tests in the `xhtml` directory are intended to be run in an XHTML fixture. That's why I also created a new template in [`test/xhtml/runner.tmpl`](https://github.com/dequelabs/axe-core/pull/582/files#diff-bffe78d0b629b92f06c8a9ee4c60d83b), and [added it to the test config](https://github.com/dequelabs/axe-core/pull/582/files#diff-6ec6d1d21440d5c0adbd37c8adec4ce7R25).

The idea is that the `xhtml` directory only contains the test specific to XHTML particularities, and the idea was intentionally to duplicate the structure of other tests.

For instance, if `test/core/utils/is-xhtml.js` contains the usual tests, run in an HTML fixture, and `test/xhtml/core/utils/is-xhtml.js` contains only the tests for `is-xhtml` that depend on an XHTML environment.

If the XHTML-specific tests were in the same directories as their HTML counterparts, they'd need an option to be ignored in the regular HTML-fixture-based tests, and enabled in the XHTML-fixture-based tests. I thought for now it would be clearer to just have to separate directory structures.

I hope it's clear 😅

Alternatively, another option would actually make aXe run **all** the existing tests both in HTML and XHTML environments. That would provide better coverage but would basically duplicate the testing time, so I thought that would be a bit aggressive.
This option would likely require to update `build/task/fixture.js` to generate both an HTML and XHTML fixtures from templates, and `build/test/config.js` to run them. (As far as I can see, I didn't dig very deep).

File: test/xhtml/core/utils/get-selector.js (hunk 3 above)
Comment (rdeltour) [reply test/xhtml/core/utils/get-selector.js]: see explanation in the general comment below 👇

File: test/xhtml/core/utils/is-xhtml.js (hunk 2 above)
Comment (rdeltour) [reply test/xhtml/core/utils/is-xhtml.js]: see explanation in the general comment below 👇

Comment (rdeltour) [reply test/xhtml/core/utils/is-xhtml.js]: specifically, this will test that the `document` **from the current fixture** is XHTML. I copied the pattern from aXe's pre-existing [`is-html5.js` tests](https://github.com/dequelabs/axe-core/blob/develop/test/commons/dom/is-html5.js#L14)

File: lib/core/utils/get-selector.js [hunk 4]
```diff
@@ -130,7 +129,9 @@ const createSelector = {
  * recognize the element by (IDs, aria roles, custom element names, etc.)
  */
 function getElmFeatures (elm, featureCount) {
-  const nodeName = elm.nodeName.toLowerCase();
+  const nodeName = escapeSelector(axe.utils.isXHTML(document)?
```
Comment (WilcoFiers) [inline lib/core/utils/get-selector.js]: We could probably just check this once at the top of the file and keep the boolean around instead of having to call this every time this method runs.

File: lib/core/utils/is-xhtml.js [hunk 5]
```diff
@@ -0,0 +1,16 @@
...
+ * @instance
+ * @param {Node} doc a document node
+ * @return {Boolean}
+ */
+axe.utils.isXHTML = function (doc) {
+	'use strict';
+	if (!doc.createElement) {
+		return false;
+	}
+	return doc.createElement('A').localName === 'A';
```
Comment (WilcoFiers) [inline lib/core/utils/is-xhtml.js]: What does this do on JSDOM? We should make sure we don't accidentally treat JSDOM as XHTML.

File: test/core/utils/is-xhtml.js [hunk 6]
```diff
@@ -0,0 +1,21 @@
+describe('axe.utils.isXHTML', function () {
```
Comment (WilcoFiers) [inline test/core/utils/is-xhtml.js]: @rdeltour Have you tested this with Edge and IE? This seems like one of those things that might not work across the board :)

File: test/xhtml/core/utils/get-selector.js (hunk 3 above)
Comment (WilcoFiers) [reply test/xhtml/core/utils/get-selector.js]: This makes sense, although I'd suggest we move it to `tests/integrations` instead.

File: Gruntfile.js [hunk 7]
```diff
@@ -281,6 +281,21 @@ module.exports = function (grunt) {
 					}
 				}
 			},
+			xhtml: {
```
Comment (WilcoFiers) [inline Gruntfile.js]: I think it would be easier to move this xhtml test into `tests/integrations`. That way we don't have to do all this scaffolding work. WDYT?

Comment (rdeltour) [reply Gruntfile.js]: these are not strictly speaking integration tests, but if you feel that will fit better there (and disturb less the code organization), sure! let me know.

File: test/core/utils/is-xhtml.js (hunk 6 above)
Comment (rdeltour) [reply test/core/utils/is-xhtml.js]: Confirmed to work on Edge and IE too.
The logic relies on the fact that HTML parsers lower-case the tag names when parsing. It's been suggested as a possible reliable option by [Anne van Kesteren on Twitter](https://twitter.com/annevk/status/922805253585690624).

File: lib/core/utils/is-xhtml.js (hunk 5 above)
Comment (rdeltour) [reply lib/core/utils/is-xhtml.js]: Yes, confirmed to work on JSDOM.

File: lib/core/utils/get-selector.js (hunk 4 above)
Comment (rdeltour) [reply lib/core/utils/get-selector.js]: > We could probably just check this once at the top of the file and keep the boolean around
where would be the best place to memoïze the boolean value? Using a `const` at the top of the file won't work.
Calling the function shouldn't be too costly in any case, so maybe it's too early an optimization?

File: Gruntfile.js (hunk 7 above)
Comment (WilcoFiers) [reply Gruntfile.js]: Yep, I think so.

File: lib/core/utils/get-selector.js (hunk 4 above)
Comment (WilcoFiers) [reply lib/core/utils/get-selector.js]: This could potentially create many thousands new elements, so I do think this is relevant. Why wouldn't a const up top work? Alternative the result can be stored in utils.isXHTML itself.

File: Gruntfile.js (hunk 7 above)
Comment (rdeltour) [reply Gruntfile.js]: ok, I'll try to update the PR accordingly (I'm currently on vacation)

File: lib/core/utils/get-selector.js (hunk 4 above)
Comment (rdeltour) [reply lib/core/utils/get-selector.js]: > Why wouldn't a const up top work?

I tried and got an error when running tests :/ But I haven't tried hard nor dug deep into the issue.

Comment (WilcoFiers) [reply lib/core/utils/get-selector.js]: @rdeltour Can you update this according what we discussed at TPAC?

**Comment by rdeltour** [comment]
> @rdeltour Any updates on this PR?

I was just working on it, in fact 😀. If time allows I will update it this afternoon.

**Comment by WilcoFiers** [comment]
@rdeltour That's good to know. We are planning to release 2.6 today and I'd like to have this in if we could. Otherwise it'll have to wait for 3.0.

**Comment by rdeltour** [comment]
@WilcoFiers ready to be reviewed!
