### PR TITLE
test: fix tests failing in IE11

### LINKED ISSUE #1384: Failing IE11 tests
Was testing some updates on Windows 10, IE 11 & in today's develop branch, these tests are failing. Our CI does not test on IE11

image

### PR DESCRIPTION
**Pull request by straker**
[Phantomjs does not support the `transform` css property](https://github.com/ariya/phantomjs/issues/12779) and so all the CSS orientation lock tests were actually false positives with the one failure being correct. Adding `-webkit-transform` fixes the problem.

IE11 also parses CSS rule property order differently so the `testutil` rule string compare would fail. Changed it to create a style on the page and compare the same properties. IE11 also didn't add a space between the CSS media properties of `(layout: portrait)`

Closes #1384

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: Stephen

### CODE REVIEW

File: lib/checks/mobile/css-orientation-lock.js [hunk 1]
```diff
@@ -87,8 +87,9 @@ Object.keys(rulesGroupByDocumentFragment).forEach(key => {
 				return;
 			}
 
-			// check if transform style exists
-			const transformStyleValue = cssRule.style.transform || false;
+			// check if transform style exists (don't forget vendor prefixes)
+			const transformStyleValue =
+				cssRule.style.transform || cssRule.style.webkitTransform || false;
```
Comment (stephenmathieson) [inline lib/checks/mobile/css-orientation-lock.js]: Looks like you've covered `-webkit-transform`, but what about `-ms-transform`?

File: test/checks/mobile/css-orientation-lock.js [hunk 2]
```diff
@@ -23,11 +21,11 @@ describe('css-orientation-lock tests', function() {
 		MEDIA_STYLE_ORIENTATION_WITHOUT_TRANSFORM:
 			'@media screen and (min-width: 1px) and (max-width: 2000px) and (orientation: portrait) { #mocha { color: red; } }',
 		MEDIA_STYLE_ORIENTATION_WITH_TRANSFORM_NOT_ROTATE:
-			'@media screen and (min-width: 1px) and (max-width: 3000px) and (orientation: landscape) { #mocha { transform: translateX(10px); } }',
+			'@media screen and (min-width: 1px) and (max-width: 3000px) and (orientation: landscape) { #mocha { transform: translateX(10px); -webkit-transform: translateX(10px); } }',
```
Comment (stephenmathieson) [inline test/checks/mobile/css-orientation-lock.js]: Please add a test using `-ms-transform`.

File: lib/checks/mobile/css-orientation-lock.js (hunk 1 above)
Comment (straker) [reply lib/checks/mobile/css-orientation-lock.js]: Good catch, forgot about IE9

File: test/checks/mobile/css-orientation-lock.js (hunk 2 above)
Comment (straker) [reply test/checks/mobile/css-orientation-lock.js]: We found out Phantomjs doesn't support `-ms-transform` since it uses a webkit engine under the hood, so we can't test this but we can add support for it in the code.

File: test/checks/mobile/css-orientation-lock.js [hunk 3]
```diff
@@ -221,29 +219,26 @@ describe('css-orientation-lock tests', function() {
 	});
 
 	// This currently breaks in IE11
```
Comment (scurker) [inline test/checks/mobile/css-orientation-lock.js]: Is this still true? If not it should be removed.

File: test/testutils.js [hunk 4]
```diff
@@ -338,10 +338,25 @@ testUtils.assertStylesheet = function assertStylesheet(
...
+		var testSheet = document.styleSheets[document.styleSheets.length - 1];
+		var sheetRule = sheet.cssRules[0];
+		var testRule = testSheet.cssRules[0];
+
+		try {
+			for (var i = 0; i < testRule.style.length; i++) {
+				var property = testRule.style[i];
+				assert.equal(sheetRule.style[property], testRule.style[property]);
+			}
+		} finally {
```
Comment (scurker) [inline test/testutils.js]: Do we really want a finally without a catch here?

Comment (straker) [reply test/testutils.js]: I want the exception to be thrown for the assert, but I always want to clean up the style.
