### PR TITLE
fix: Allow divs as groups in dl

### LINKED ISSUE #262: Support expanded definition list rule in the WHATWG HTML spec which allows for divs as parents of dt/dds
I was wondering if the definition list rule would or should ever be expanded to the WHATWG HTML spec which seems to allow for divs as parents of dt/dds (https://html.spec.whatwg.org/multipage/semantics.html#the-dl-element) if screen readers/browsers support this (I don't know if they do)? I imagine the WCAG is strict to the W3C's HTML5 spec, but don't know for sure. 

I've had this come up and trying to figure out how to avoid disabling this rule or find some other semantic markup for the relationships given the divs can't be changed.

### PR DESCRIPTION
**Pull request by WilcoFiers**
Allow div elements to group content inside of dl elements.

Closes #262

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: Jey

### CODE REVIEW

File: test/checks/lists/only-dlitems.js [hunk 1]
```diff
@@ -176,6 +176,24 @@ describe('only-dlitems', function() {
...
+	it('should return false if the list has dt and dd inside a div group', function() {
+		var checkArgs = checkSetup(
+			'<dl id="target"><div><dt>An item</dt><dd>A list</dd></div></dl>'
+		);
+		assert.isFalse(
+			checks['only-dlitems'].evaluate.apply(checkContext, checkArgs)
+		);
+	});
+
+	it('should return true if the list has dt and dd inside a div group with a role', function() {
```
Comment (dylanb) [inline test/checks/lists/only-dlitems.js]: What about a test with other content inside the div?

Comment (WilcoFiers) [reply test/checks/lists/only-dlitems.js]: Resolving in a new PR
