### PR TITLE
Region: allow forms with non-empty title, plain div[role=form]

### LINKED ISSUE #962: False positive: 'region' rule fails for <form> elements with non-empty "title" attribute
This issue is related to #723 

```<form>``` elements with non empty title should be considered as ```form``` landmarks

- Demo:
```
<form id="1" title="name 3">A form element with a non-empty title</form>
```
<pre><code>
axe-core version: 3.0.3
axe-Coconut version: 3.4.0-alpha.2

</code></pre>

### PR DESCRIPTION
**Pull request by marcysutton**
Form elements with a title attribute are now counted as landmarks, whereas forms without a label or title are not. ARIA forms are counted as landmarks regardless of label or title.

Closes  #962 

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [x] Follows the commit message policy, appropriate for next version
- [x] Has documentation updated, a DU ticket, or requires no documentation change
- [x] Includes new tests, or was unnecessary
- [x] Code is reviewed for security by: @wilcofiers

### CODE REVIEW

File: lib/checks/navigation/region.js [hunk 1]
```diff
@@ -30,16 +30,14 @@ function isLandmark(virtualNode) {
...
-		}
 		return landmarkRoles.includes(explictRole);
 	} else {
 		// Check if the node matches any of the CSS selectors of implicit landmarks
 		return implicitLandmarks.some(implicitSelector => {
 			let matches = axe.utils.matchesSelector(node, implicitSelector);
 			if (node.tagName.toLowerCase() === 'form') {
-				return matches && !!aria.labelVirtual(virtualNode);
+				let title = node.getAttribute('title') || '';
+				return matches && (!!aria.labelVirtual(virtualNode) || !!axe.commons.text.sanitize(title) );
```
Comment (jkodu) [inline lib/checks/navigation/region.js]: minor detail, why aim to sanitize title if tile is empty (in some cases)? worth adding an && to check for that.

Comment (marcysutton) [reply lib/checks/navigation/region.js]: Ok, I pushed another commit to not sanitize empty strings.
